# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/Sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/Sirupsen/logrus";
      rev = "d26492970760ca5d33129d2d799e34be5c4782eb";
      sha256 = "05nyb0h9b9sv5hz7lp74d85bryhqzjy1q22dhszai48634ix0fms";
    };
  }
  {
    goPackagePath = "github.com/codegangsta/cli";
    fetch = {
      type = "git";
      url = "https://github.com/codegangsta/cli";
      rev = "0bdeddeeb0f650497d603c4ad7b20cfe685682f6";
      sha256 = "1ny63c7bfwfrsp7vfkvb4i0xhq4v7yxqnwxa52y4xlfxs4r6v6fg";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "6d212800a42e8ab5c146b8ace3490ee17e5225f9";
      sha256 = "01i0n1s4j7khb7n6mz2wymniz37q0vbzkgfv7rbi6p9hpg227q93";
    };
  }
  {
    goPackagePath = "github.com/fatih/color";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/color";
      rev = "9ab0325f4904aac7c2c60db3cff3b35f415575c7";
      sha256 = "041kkanp94bjsacpdzsibqhssdsvxqlnk0441a7w0qfla4rvyp52";
    };
  }
  {
    goPackagePath = "github.com/fatih/structs";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/structs";
      rev = "dc3312cb1a4513a366c4c9e622ad55c32df12ed3";
      sha256 = "0wgm6shjf6pzapqphs576dv7rnajgv580rlp0n08zbg6fxf544cd";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/errwrap";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/errwrap";
      rev = "7554cd9344cec97297fa6649b055a8c98c2a1e55";
      sha256 = "0kmv0p605di6jc8i1778qzass18m0mv9ks9vxxrfsiwcp4la82jf";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-cleanhttp";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-cleanhttp";
      rev = "ad28ea4487f05916463e2423a55166280e8254b5";
      sha256 = "0xw0qas3ixg8p2xh09hhc81km0mfn9lbnfgrdb309hzcwhmiyqjm";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-multierror";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-multierror";
      rev = "8484912a3b9987857bac52e0c5fec2b95f419628";
      sha256 = "02srjgqmar50an8gxlif4fybyxjlypk27p2pmghnm7050phil9kc";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-rootcerts";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-rootcerts";
      rev = "6bb64b370b90e7ef1fa532be9e591a81c3493e00";
      sha256 = "1a81fcm1i0ji2iva0dcimiichgwpbcb7lx0vyaks87zj5wf04qy9";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "7cb7455c285ca3bf3362aa4ba6a06a6d6f5c3ba0";
      sha256 = "0a2x6xrmypavydggwlws9xvp2dqp0xprfjzd5bfsx1wgil9rgs71";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/vault";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/vault";
      rev = "f4adc7fa960ed8e828f94bc6785bcdbae8d1b263";
      sha256 = "0rrrzkza12zbbfc24q4q7ygfczq1j8ljsjagsa8vpp3375dflzdy";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "d228849504861217f796da67fae4f6e347643f15";
      sha256 = "0ch5sfcpmqczsh8kjbwpzdw31lacbkfyzvpzh4disnhhydbxjq0d";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "30a891c33c7cde7b02a981314b4228ec99380cca";
      sha256 = "03gsxn89pgkj4jkxm9avnj4f0ckvcskc6fj2lcd98l3akrz50ndg";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "756f7b183b7ab78acdbbee5c7f392838ed459dda";
      sha256 = "0yd3682x22lqrfq4h0q16c4swcfn3lmds05ijynm2fk1gcbnwiqn";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "f3009df150dadf309fdee4a54ed65c124afad715";
      sha256 = "1i08zzlsn1bwicjn8cvakv2h5wwicw8ijx0i0cipk49yfmd6ab4i";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "d8ed2627bdf02c080bf22230dbb337003b7aba2d";
      sha256 = "0w1jp4k4zbnrxh3jvh8fgbjgqpf2hg31pbj8fb32kh26px9ldpbs";
    };
  }
  {
    goPackagePath = "github.com/sethgrid/pester";
    fetch = {
      type = "git";
      url = "https://github.com/sethgrid/pester";
      rev = "2a102734c18c43c74fd0664e06cd414cf9602b93";
      sha256 = "1m94magz9ylm7ccdb7l6qhq6p79psqh0dc094yh5hkqamjrjhwy7";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "69483b4bd14f5845b5a1e55bca19e954e827f1d0";
      sha256 = "11lzrwkdzdd8yyag92akncc008h2f9d1bpc489mxiwp0jrmz4ivb";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9";
      sha256 = "04va4pqygfzr89fx873k44bmivk7nybqalybi6q96lnn45h2scbr";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "53feefa2559fb8dfa8d81baad31be332c97d6c77";
      sha256 = "1afspdzgq5p1803fnzjyx0is75vjbsxkj9wq1dgz5jcz4wi764hg";
    };
  }
]
