# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "vault-sync-unstable-${version}";
  version = "2018-01-10";

  goPackagePath = "github.com/cloudwatt/vault-sync";

  src = fetchgit {
    rev = "1594202e5a02d6692afffbac1d5c7cf1a21475c6";
    url = "https://github.com/cloudwatt/vault-sync";
    sha256 = "16qp17xfrk3iqp8vz1dvin9i679a4fb9y54qijz56irlxxgialcq";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
