# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "calicoctl-unstable-${version}";
  version = "2018-11-20";
  rev = "8f0c1be58258b71d17f7c92d7e66b3e16b5a9593";

  goPackagePath = "github.com/projectcalico/calicoctl";

  src = fetchFromGitHub {
    inherit rev;
    owner = "projectcalico";
    repo = "calicoctl";
    sha256 = "0p7k1wrkq61zb8kdmylgsjnwq0ndi9a6f73f3pk10rn2r57rafwc";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta =  with stdenv.lib; {
    maintainers = with maintainers; [ k-ayache ];
  };
}
