# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
{ pkgs, stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "cni-plugin-${version}";
  version = "3.2.3";

  goPackagePath = "github.com/projectcalico/cni-plugin";

  src = fetchgit {
    rev = "312c9f458c63bc6d898507d68f5a0ffa4c0e02a9";
    url = "https://github.com/projectcalico/cni-plugin.git";
    sha256 = "1h7w3x63bdf8r7jfwx7abhmidq5wb24dfz6phyky5rvl50kdkxap";
  };

  buildPhase = ''
    rm -rf $NIX_BUILD_TOP/go/src/github.com/containernetworking/plugins/vendor/
    cd $NIX_BUILD_TOP/go/src/github.com/projectcalico/cni-plugin
	go build -v -i -o $NIX_BUILD_TOP/go/bin/calico calico.go
	go build -v -i -o $NIX_BUILD_TOP/go/bin/calico-ipam ipam/calico-ipam.go
  '';

  goDeps = ./deps.nix;

}
